apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: syvora-app-monitor
  namespace: monitoring
  labels:
    release: monitoring        # must match your Prometheus release name
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: syvora-app   # must match your app Service labels
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s

